import { StyleSheet } from "react-native";
import { theme } from "../constants/theme";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F5F8F4" },
  header: { padding: theme.spacing.lg, paddingTop: theme.spacing.xl, backgroundColor: "#FFFFFF", borderBottomWidth: 1, borderBottomColor: "#E5E7EB" },
  title: { fontSize: 22, fontWeight: "bold", color: "#234919" },
  subtitle: { fontSize: 13, color: "#6B7280", marginTop: 2 },
  filterRow: { flexDirection: "row", paddingHorizontal: theme.spacing.lg, paddingVertical: theme.spacing.md, gap: 6 },
  filterChip: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 16, backgroundColor: "#E5E7EB" },
  filterChipSelected: { backgroundColor: "#234919" },
  filterChipText: { fontSize: 12, fontWeight: "600", color: "#4B5563" },
  filterChipTextSelected: { color: "#FFFFFF" },
  loadingBox: { flex: 1, justifyContent: "center", alignItems: "center" },
  listContent: { padding: theme.spacing.lg },
  card: { backgroundColor: "#FFFFFF", borderRadius: theme.borderRadius.md, padding: theme.spacing.md, marginBottom: theme.spacing.md, borderWidth: 1, borderColor: "#E5E7EB" },
  cardHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 4 },
  cardTitle: { fontSize: 15, fontWeight: "bold", color: "#1A1D1A", flex: 1 },
  statusBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6, marginLeft: 6 },
  bgYellow: { backgroundColor: "#FEF3C7" },
  bgBlue: { backgroundColor: "#DBEAFE" },
  bgGreen: { backgroundColor: "#D1FAE5" },
  statusText: { fontSize: 11, fontWeight: "bold" },
  textYellow: { color: "#D97706" },
  textBlue: { color: "#1D4ED8" },
  textGreen: { color: "#065F46" },
  userText: { fontSize: 12, color: "#4B5563", marginBottom: 4 },
  bold: { fontWeight: "bold", color: "#1A1D1A" },
  catTag: { fontSize: 11, color: "#6B7280", fontWeight: "600", marginBottom: 4 },
  cardDesc: { fontSize: 13, color: "#4B5563", lineHeight: 18, marginBottom: theme.spacing.xs },
  respuestaBox: { backgroundColor: "#F0FDF4", padding: 8, borderRadius: 6, borderWidth: 1, borderColor: "#BBF7D0", marginVertical: 6 },
  respuestaTitle: { fontSize: 12, fontWeight: "bold", color: "#166534" },
  respuestaText: { fontSize: 12, color: "#14532D" },
  actionRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: theme.spacing.xs },
  dateText: { fontSize: 11, color: "#9CA3AF" },
  manageBtn: { backgroundColor: "#234919", paddingHorizontal: 10, paddingVertical: 6, borderRadius: theme.borderRadius.md },
  manageBtnText: { color: "#FFFFFF", fontSize: 12, fontWeight: "bold" },
  emptyBox: { alignItems: "center", paddingVertical: theme.spacing.xl },
  emptyIcon: { fontSize: 40, marginBottom: theme.spacing.sm },
  emptyTitle: { fontSize: 16, fontWeight: "bold", color: "#1A1D1A" },
  modalOverlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.5)", justifyContent: "center", padding: theme.spacing.lg },
  modalContent: { backgroundColor: "#FFFFFF", borderRadius: theme.borderRadius.lg, padding: theme.spacing.lg },
  modalTitle: { fontSize: 18, fontWeight: "bold", color: "#234919" },
  modalSubtitle: { fontSize: 13, color: "#6B7280", marginVertical: 2 },
  modalLabel: { fontSize: 13, fontWeight: "600", color: "#1A1D1A", marginTop: theme.spacing.md, marginBottom: 4 },
  statusOptionsRow: { flexDirection: "row", gap: 6, marginBottom: theme.spacing.sm },
  statusOptBtn: { flex: 1, paddingVertical: 8, borderRadius: theme.borderRadius.md, borderWidth: 1, borderColor: "#E5E7EB", alignItems: "center", backgroundColor: "#F9FAFB" },
  statusOptBtnSelected: { backgroundColor: "#234919", borderColor: "#234919" },
  statusOptText: { fontSize: 12, fontWeight: "600", color: "#4B5563" },
  statusOptTextSelected: { color: "#FFFFFF" },
  modalInput: { borderWidth: 1, borderColor: "#E5E7EB", borderRadius: theme.borderRadius.md, padding: theme.spacing.sm, fontSize: 14, minHeight: 60, textAlignVertical: "top" },
  modalActions: { flexDirection: "row", marginTop: theme.spacing.lg, gap: 10 },
  cancelBtn: { flex: 1, height: 42, backgroundColor: "#E5E7EB", borderRadius: theme.borderRadius.md, alignItems: "center", justifyContent: "center" },
  cancelBtnText: { color: "#4B5563", fontWeight: "bold" },
  confirmBtn: { flex: 1, height: 42, backgroundColor: "#234919", borderRadius: theme.borderRadius.md, alignItems: "center", justifyContent: "center" },
  confirmBtnText: { color: "#FFFFFF", fontWeight: "bold" },
});
