import { StyleSheet } from "react-native";
import { theme } from "../constants/theme";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F5F8F4" },
  header: { padding: theme.spacing.lg, paddingTop: theme.spacing.xl, backgroundColor: "#FFFFFF", borderBottomWidth: 1, borderBottomColor: "#E5E7EB" },
  title: { fontSize: 22, fontWeight: "bold", color: "#234919" },
  subtitle: { fontSize: 13, color: "#6B7280", marginTop: 2 },
  searchContainer: { paddingHorizontal: theme.spacing.lg, paddingTop: theme.spacing.md },
  searchInput: { height: 44, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E5E7EB", borderRadius: theme.borderRadius.md, paddingHorizontal: theme.spacing.md, fontSize: 14, color: "#1A1D1A" },
  filterRow: { flexDirection: "row", paddingHorizontal: theme.spacing.lg, paddingVertical: theme.spacing.md, gap: 6 },
  filterChip: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 16, backgroundColor: "#E5E7EB" },
  filterChipSelected: { backgroundColor: "#234919" },
  filterChipText: { fontSize: 12, fontWeight: "600", color: "#4B5563" },
  filterChipTextSelected: { color: "#FFFFFF" },
  loadingBox: { flex: 1, justifyContent: "center", alignItems: "center" },
  listContent: { padding: theme.spacing.lg, paddingTop: 0 },
  userCard: { backgroundColor: "#FFFFFF", borderRadius: theme.borderRadius.md, padding: theme.spacing.md, marginBottom: theme.spacing.md, borderWidth: 1, borderColor: "#E5E7EB" },
  userCardHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start" },
  userInfo: { flex: 1 },
  userName: { fontSize: 16, fontWeight: "bold", color: "#1A1D1A" },
  userSubtext: { fontSize: 12, color: "#6B7280", marginTop: 2 },
  statusBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6 },
  bgGreen: { backgroundColor: "#D1FAE5" }, bgYellow: { backgroundColor: "#FEF3C7" }, bgRed: { backgroundColor: "#FEE2E2" },
  statusBadgeText: { fontSize: 11, fontWeight: "bold" },
  textGreen: { color: "#065F46" }, textYellow: { color: "#D97706" }, textRed: { color: "#991B1B" },
  userDetailsRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: theme.spacing.sm },
  inmuebleBadgeBox: { backgroundColor: "#E5EAE2", paddingHorizontal: 8, paddingVertical: 4, borderRadius: 4 },
  inmuebleBadgeText: { fontSize: 12, fontWeight: "bold", color: "#234919" },
  roleText: { fontSize: 12, color: "#6B7280" },
  motivoBox: { marginTop: theme.spacing.sm, backgroundColor: "#FEF2F2", padding: 8, borderRadius: 6, borderWidth: 1, borderColor: "#FCA5A5" },
  motivoTitle: { fontSize: 11, fontWeight: "bold", color: "#991B1B" },
  motivoContent: { fontSize: 12, color: "#7F1D1D" },
  actionsRow: { flexDirection: "row", marginTop: theme.spacing.md, gap: 8 },
  actionBtn: { flex: 1, height: 38, borderRadius: theme.borderRadius.md, alignItems: "center", justifyContent: "center" },
  approveBtn: { backgroundColor: "#5CA838" }, suspendBtn: { backgroundColor: "#EF4444" }, reactivateBtn: { backgroundColor: "#234919" },
  actionBtnText: { color: "#FFFFFF", fontSize: 13, fontWeight: "bold" },
  emptyBox: { alignItems: "center", paddingVertical: theme.spacing.xl },
  emptyText: { color: "#6B7280", fontSize: 14 },
  modalOverlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.5)", justifyContent: "center", padding: theme.spacing.lg },
  modalContent: { backgroundColor: "#FFFFFF", borderRadius: theme.borderRadius.lg, padding: theme.spacing.lg },
  modalTitle: { fontSize: 18, fontWeight: "bold", color: "#991B1B" },
  modalSubtitle: { fontSize: 13, color: "#6B7280", marginVertical: 4 },
  modalInputLabel: { fontSize: 13, fontWeight: "600", color: "#1A1D1A", marginTop: theme.spacing.md, marginBottom: 4 },
  modalInput: { borderWidth: 1, borderColor: "#E5E7EB", borderRadius: theme.borderRadius.md, padding: theme.spacing.sm, fontSize: 14, minHeight: 60, textAlignVertical: "top" },
  modalActions: { flexDirection: "row", marginTop: theme.spacing.lg, gap: 10 },
  modalCancelBtn: { flex: 1, height: 42, backgroundColor: "#E5E7EB", borderRadius: theme.borderRadius.md, alignItems: "center", justifyContent: "center" },
  modalCancelBtnText: { color: "#4B5563", fontWeight: "bold" },
  modalConfirmBtn: { flex: 1, height: 42, backgroundColor: "#EF4444", borderRadius: theme.borderRadius.md, alignItems: "center", justifyContent: "center" },
  modalConfirmBtnText: { color: "#FFFFFF", fontWeight: "bold" },
});
