import { StyleSheet } from "react-native";
import { theme } from "../constants/theme";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F5F8F4" },
  header: { flexDirection: "row", alignItems: "center", padding: theme.spacing.md, paddingTop: theme.spacing.xl, backgroundColor: "#FFFFFF", borderBottomWidth: 1, borderBottomColor: "#E5E7EB" },
  backBtn: { paddingRight: theme.spacing.md },
  backBtnText: { color: "#234919", fontSize: 15, fontWeight: "bold" },
  headerTitleBox: { flex: 1 },
  headerTitle: { fontSize: 16, fontWeight: "bold", color: "#1A1D1A" },
  headerSubtitle: { fontSize: 12, color: "#6B7280" },
  loadingBox: { flex: 1, justifyContent: "center", alignItems: "center" },
  listContent: { padding: theme.spacing.md, paddingBottom: theme.spacing.lg },
  messageBubbleContainer: { marginBottom: theme.spacing.sm, width: "100%" },
  myMessageContainer: { alignItems: "flex-end" },
  theirMessageContainer: { alignItems: "flex-start" },
  messageBubble: { maxWidth: "80%", borderRadius: 16, padding: theme.spacing.md },
  myBubble: { backgroundColor: "#5CA838", borderBottomRightRadius: 2 },
  theirBubble: { backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E5E7EB", borderBottomLeftRadius: 2 },
  messageText: { fontSize: 14, lineHeight: 20 },
  myMessageText: { color: "#FFFFFF" },
  theirMessageText: { color: "#1A1D1A" },
  messageTime: { fontSize: 10, marginTop: 4, textAlign: "right" },
  myMessageTime: { color: "#E5EAE2" },
  theirMessageTime: { color: "#9CA3AF" },
  inputContainer: { flexDirection: "row", alignItems: "center", padding: theme.spacing.sm, backgroundColor: "#FFFFFF", borderTopWidth: 1, borderTopColor: "#E5E7EB" },
  input: { flex: 1, minHeight: 40, maxHeight: 100, backgroundColor: "#FAFAFA", borderWidth: 1, borderColor: "#E5E7EB", borderRadius: 20, paddingHorizontal: theme.spacing.md, fontSize: 14, color: "#1A1D1A", marginRight: theme.spacing.sm },
  sendBtn: { width: 60, height: 40, backgroundColor: "#234919", borderRadius: 20, alignItems: "center", justifyContent: "center" },
  sendBtnDisabled: { opacity: 0.5 },
  sendBtnText: { color: "#FFFFFF", fontSize: 13, fontWeight: "bold" },
  emptyBox: { alignItems: "center", paddingVertical: theme.spacing.xl },
  emptyIcon: { fontSize: 40, marginBottom: theme.spacing.sm },
  emptyTitle: { fontSize: 16, fontWeight: "bold", color: "#1A1D1A" },
  emptySubtitle: { fontSize: 13, color: "#6B7280", textAlign: "center", marginTop: 4 },
  modalOverlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.5)", justifyContent: "center", padding: theme.spacing.lg },
  modalContent: { backgroundColor: "#FFFFFF", borderRadius: theme.borderRadius.lg, padding: theme.spacing.lg },
  modalTitle: { fontSize: 18, fontWeight: "bold", color: "#991B1B" },
  modalSubtitle: { fontSize: 13, color: "#6B7280", marginVertical: 2 },
  msgPreviewBox: { backgroundColor: "#F9FAFB", padding: theme.spacing.sm, borderRadius: 6, borderWidth: 1, borderColor: "#E5E7EB", marginVertical: theme.spacing.sm },
  msgPreviewText: { fontSize: 13, fontStyle: "italic", color: "#4B5563" },
  modalLabel: { fontSize: 13, fontWeight: "600", color: "#1A1D1A", marginBottom: 4 },
  modalInput: { borderWidth: 1, borderColor: "#E5E7EB", borderRadius: theme.borderRadius.md, padding: theme.spacing.sm, fontSize: 14, minHeight: 60, textAlignVertical: "top" },
  modalActions: { flexDirection: "row", marginTop: theme.spacing.lg, gap: 10 },
  cancelBtn: { flex: 1, height: 42, backgroundColor: "#E5E7EB", borderRadius: theme.borderRadius.md, alignItems: "center", justifyContent: "center" },
  cancelBtnText: { color: "#4B5563", fontWeight: "bold" },
  confirmBtn: { flex: 1, height: 42, backgroundColor: "#EF4444", borderRadius: theme.borderRadius.md, alignItems: "center", justifyContent: "center" },
  confirmBtnText: { color: "#FFFFFF", fontWeight: "bold" },
});
