import { StyleSheet } from "react-native";
import { theme } from "../constants/theme";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F5F8F4" },
  scrollContent: { padding: theme.spacing.lg, paddingTop: theme.spacing.xl },
  header: { marginBottom: theme.spacing.lg },
  headerTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  title: { fontSize: 18, fontWeight: "bold", color: "#234919" },
  subtitle: { fontSize: 13, color: "#6B7280", marginTop: 2 },
  adminBtn: {
    backgroundColor: "#E5EAE2",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  adminBtnText: { fontSize: 12, fontWeight: "bold", color: "#234919" },
  formCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: theme.borderRadius.lg,
    padding: theme.spacing.lg,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    marginBottom: theme.spacing.xl,
  },
  formTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#1A1D1A",
    marginBottom: theme.spacing.xs,
  },
  label: {
    fontSize: 13,
    fontWeight: "600",
    color: "#1A1D1A",
    marginTop: theme.spacing.md,
    marginBottom: 4,
  },
  catScroll: { flexDirection: "row", marginBottom: theme.spacing.xs },
  catChip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: "#F3F4F6",
    marginRight: 8,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  catChipSelected: { backgroundColor: "#234919", borderColor: "#234919" },
  catChipText: { fontSize: 13, fontWeight: "600", color: "#4B5563" },
  catChipTextSelected: { color: "#FFFFFF" },
  input: {
    height: 46,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: theme.borderRadius.md,
    paddingHorizontal: theme.spacing.md,
    fontSize: 14,
    color: "#1A1D1A",
    backgroundColor: "#FAFAFA",
  },
  textArea: {
    height: 80,
    paddingTop: theme.spacing.sm,
    textAlignVertical: "top",
  },
  submitBtn: {
    height: 48,
    backgroundColor: "#5CA838",
    borderRadius: theme.borderRadius.md,
    alignItems: "center",
    justifyContent: "center",
    marginTop: theme.spacing.lg,
  },
  btnDisabled: { opacity: 0.7 },
  submitBtnText: { color: "#FFFFFF", fontSize: 15, fontWeight: "bold" },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#234919",
    marginBottom: theme.spacing.md,
  },
  loadingBox: { paddingVertical: theme.spacing.xl, alignItems: "center" },
  incidenciaCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: theme.borderRadius.md,
    padding: theme.spacing.md,
    marginBottom: theme.spacing.md,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 4,
  },
  cardTitle: { fontSize: 15, fontWeight: "bold", color: "#1A1D1A", flex: 1 },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    marginLeft: 6,
  },
  bgYellow: { backgroundColor: "#FEF3C7" },
  bgBlue: { backgroundColor: "#DBEAFE" },
  bgGreen: { backgroundColor: "#D1FAE5" },
  statusText: { fontSize: 11, fontWeight: "bold" },
  textYellow: { color: "#D97706" },
  textBlue: { color: "#1D4ED8" },
  textGreen: { color: "#065F46" },
  categoryText: {
    fontSize: 11,
    color: "#6B7280",
    fontWeight: "600",
    marginBottom: 4,
  },
  cardDesc: {
    fontSize: 13,
    color: "#4B5563",
    lineHeight: 18,
    marginBottom: theme.spacing.xs,
  },
  respuestaBox: {
    backgroundColor: "#F0FDF4",
    padding: 8,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "#BBF7D0",
    marginVertical: 6,
  },
  respuestaTitle: { fontSize: 12, fontWeight: "bold", color: "#166534" },
  respuestaText: { fontSize: 12, color: "#14532D" },
  dateText: { fontSize: 11, color: "#9CA3AF", textAlign: "right" },
  emptyBox: { alignItems: "center", paddingVertical: theme.spacing.xl },
  emptyIcon: { fontSize: 40, marginBottom: theme.spacing.sm },
  emptyTitle: { fontSize: 16, fontWeight: "bold", color: "#1A1D1A" },
  emptySubtitle: {
    fontSize: 13,
    color: "#6B7280",
    textAlign: "center",
    marginTop: 4,
  },
});
