import { StyleSheet } from "react-native";
import { theme } from "../constants/theme";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F5F8F4" },
  scrollContent: { padding: theme.spacing.lg, paddingTop: theme.spacing.xl },
  header: { alignItems: "center", marginBottom: theme.spacing.lg },
  title: { fontSize: 24, fontWeight: "bold", color: "#234919" },
  subtitle: { fontSize: 13, color: "#6B7280", textAlign: "center", marginTop: theme.spacing.xs },
  card: { backgroundColor: "#FFFFFF", borderRadius: theme.borderRadius.lg, padding: theme.spacing.lg, borderWidth: 1, borderColor: "#E5E7EB" },
  sectionHeader: { fontSize: 15, fontWeight: "bold", color: "#234919", marginTop: theme.spacing.md, marginBottom: theme.spacing.xs, borderBottomWidth: 1, borderBottomColor: "#E5E7EB", paddingBottom: 4 },
  label: { fontSize: 13, fontWeight: "600", color: "#1A1D1A", marginBottom: 4, marginTop: theme.spacing.sm },
  input: { height: 46, borderWidth: 1, borderColor: "#E5E7EB", borderRadius: theme.borderRadius.md, paddingHorizontal: theme.spacing.md, fontSize: 14, color: "#1A1D1A", backgroundColor: "#FAFAFA" },
  selectorRow: { flexDirection: "row", gap: theme.spacing.sm, marginBottom: theme.spacing.xs },
  optionButton: { flex: 1, height: 44, borderWidth: 1, borderColor: "#E5E7EB", borderRadius: theme.borderRadius.md, alignItems: "center", justifyContent: "center", backgroundColor: "#F9FAFB" },
  optionButtonSelected: { backgroundColor: "#234919", borderColor: "#234919" },
  optionButtonText: { fontSize: 14, fontWeight: "600", color: "#4B5563" },
  optionButtonTextSelected: { color: "#FFFFFF" },
  horizontalScroll: { flexDirection: "row", marginBottom: theme.spacing.xs },
  chipButton: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 20, backgroundColor: "#F3F4F6", marginRight: 8, borderWidth: 1, borderColor: "#E5E7EB" },
  chipButtonSelected: { backgroundColor: "#5CA838", borderColor: "#5CA838" },
  chipText: { fontSize: 13, fontWeight: "600", color: "#4B5563" },
  chipTextSelected: { color: "#FFFFFF" },
  selectorGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: theme.spacing.sm },
  gridButton: { width: "30%", paddingVertical: 10, borderRadius: theme.borderRadius.md, backgroundColor: "#F9FAFB", borderWidth: 1, borderColor: "#E5E7EB", alignItems: "center", justifyContent: "center" },
  gridButtonSelected: { backgroundColor: "#5CA838", borderColor: "#5CA838" },
  gridButtonText: { fontSize: 13, fontWeight: "600", color: "#4B5563" },
  gridButtonTextSelected: { color: "#FFFFFF" },
  codePreviewBox: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", backgroundColor: "#F5F8F4", padding: theme.spacing.md, borderRadius: theme.borderRadius.md, borderWidth: 1, borderColor: "#D1E7DD", marginTop: theme.spacing.xs },
  codePreviewLabel: { fontSize: 14, color: "#234919", fontWeight: "600" },
  codePreviewValue: { fontSize: 16, fontWeight: "bold", color: "#5CA838" },
  button: { height: 48, backgroundColor: "#5CA838", borderRadius: theme.borderRadius.md, alignItems: "center", justifyContent: "center", marginTop: theme.spacing.lg },
  buttonDisabled: { opacity: 0.7 },
  buttonText: { color: "#FFFFFF", fontSize: 16, fontWeight: "bold" },
  footerRow: { flexDirection: "row", justifyContent: "center", marginTop: theme.spacing.lg },
  footerText: { fontSize: 14, color: "#6B7280" },
  linkText: { fontSize: 14, fontWeight: "bold", color: "#234919" },
});
